# Generated by Django 4.2.1 on 2023-05-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3, verbose_name='Title')),
                ('fullname', models.CharField(max_length=50, verbose_name='fullname')),
                ('member', models.BooleanField(default=False)),
                ('address', models.TextField(max_length=150, verbose_name='address of member')),
                ('image', models.FilePathField(path='/image')),
                ('phone', models.BigIntegerField(default=False)),
            ],
        ),
    ]
